---
title: "Assignment 3"
author: "Sage Davis"
date: "2023-03-03"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(purrr)
library(ggpubr)
```

# Our highway

3 car types 

Imagine with have 4 different car types - and we know how often each occurs:

* car A  mass 20000 kg, area 22 m^2

* car B mass 65000 kg, area 30 m^2

* car C mass 38000 kg, area 22 m^2

* car D mass 5,000 kg, area 10 m^2 

Mean highway speed is 80 km/hr w/ sd = 10 m^2

```{r sampling2, eval=TRUE, echo=TRUE}

source("../R/autopower.R")

# generate a structure to store info on our possible cars
possible_cars = data.frame(name = c("A","B","C","D"),mass=c(10000,65000,38000,5000), area = c(22,30,22,10))

# do conversion from km/h to m/s
speed_base = 80 * 0.278
speed_sd = 10 * 0.278

# because I have one mass and area for each car and only 1 speed
# I can estimate power for each car type
# add to the data structure
possible_cars$power = autopower(V=speed_base, A = possible_cars$area, m=possible_cars$mass)

head(possible_cars)

```
Part a) For Loop

```{r withforloop}

# the first part, generating speeds is the same
# what is I want to estimate average power use given each car

possible_cars

# use sample to generate a distribution of speeds

# assume a normal distribution of speeds with mean 80km/hr and sd 10km/hr
# lets get a sample of a 200 speeds- we could also do this by actually measuring speeds

nsample = 200

speeds = rnorm(mean=speed_base, sd=speed_sd, n=nsample)
summary(speeds)

# what does the speed distribution look like
plot(density(speeds), ylab="Distribution of Speeds in (m/s)")


# we use a for loop to cycle through
# we need to create a data frame to store results - as above
# one column for each car and one row for each speed

powerall_a = as.data.frame(matrix(nrow=length(speeds), ncol=nrow(possible_cars)))

# because we don't initialize it - values are NA
head(powerall_a)

# how many cars area there - 4 check
nrow(possible_cars)

# for loops use an index - in this case "i" but you could use anything - it repeats
# anything between the {} for each values of i between 1 and nrow(possible_car) (which is 4 in our case)

# index in to a matrix (like powerall_a) is by row and column powerall_a[2,5] is 2nd row and 5th column
for (i in 1:nrow(possible_cars)) {
  powerall_a[,i] = autopower(A=possible_cars$area[i], m=possible_cars$mass[i], V=speeds)
}

# now it looks like above
head(powerall_a)

# add column names
colnames(powerall_a)=possible_cars$name

# for plotting sometimes its useful to turn columns in to rows
powerallr_a = powerall_a %>% pivot_longer(cols=everything(), names_to="car", values_to="power")
head(powerallr_a)

# quick visualization

method1_plot = ggplot(powerallr_a, aes(car,power, fill=car))+geom_boxplot()+ggtitle("for loop")
method1_plot

# Summary of for loop analysis
summary(powerallr_a)


```
Part 2) - Use pmap

```{r withpmap}

# the first part, generating speeds is the same
# what is I want to estimate average power use given  each car

possible_cars

# the first part is the same as above
# use sample to generate a distribution of speeds

# assume a log normal distribution of speeds with mean 100km/hr
# recall our function needs speed in m/s not km/hr so we will also do a conversion
# lets get a sample of a 200 speeds- we could also do this by actually measuring speeds

#nsample = 200
#mean_speed = log(100*0.277)

#speeds = rlnorm(mean=mean_speed, sd=0.1*mean_speed, nsample)
#summary(speeds)

#plot(density(speeds), ylab="Distribution of Speeds in (m/s)")


# how do we run each car for all speeds 
# pmap runs a function for each value in a list of parameters, with other parameters set for each iteration


powerall_b = pmap(list(A = possible_cars$area, m=possible_cars$mass), autopower, V=speeds)

# lets turn to a data frame for easier graphing
# we can add column names
powerall_b = as.data.frame(powerall_b, col.names=possible_cars$name)

head(powerall_b)


# for plotting sometimes its useful to turn columns in to rows
powerallr_b = powerall_b %>% pivot_longer(cols=everything(), names_to="car", values_to="power")

head(powerallr_b)

# quick visualization

method2_plot = ggplot(powerallr_b, aes(car,power, fill=car))+geom_boxplot()+ggtitle("pmap")
method2_plot

# put plots side by side
# to confirm that they look similar
ggarrange(method1_plot, method2_plot)

# compare values
head(powerallr_a)
head(powerallr_b)

# not exactly the same - why?
# recall that we sample speeds!

# but we can compare means (also using  map :)
# map runs the function (here - mean), over each column 
# they are close but still not exact, so statistics such as means and quantiles are # similar, and relative difference between cars is the same
powerall_a %>% map(mean)
powerall_b %>% map(mean)

# upper 90% quantile
powerall_a %>% map(quantile, probs=0.9)
powerall_b %>% map(quantile, probs=0.9)

summary(powerallr_a)
summary(powerallr_b)
```
