---
title: "Assignment 5"
author: "Sage Davis, Kristin Art, Daija Odom"
date: "2023-03-08"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(purrr)
library(ggpubr)
library(dplyr)
library(tidyr)
library(testthat)
```

```{r}
# source plant growth function
source("../R/compute_plant_growth.R")

# error check function, make sun = -1
compute_plant_growth(sun = -1,water = 0)

# error check function, make water = -1
compute_plant_growth(sun = 0,water = -1)

# test function output
test_file("../tests/test_compute_plant_growth.R")
```

```{r}
# generate data inputs, one for each week of the year
nsample = 52

# mean number of waterings per week
water_mean = 2

# sd waterings per week
water_sd = 0.5

# waterings per week
water = rnorm(mean=water_mean, sd=water_sd, n=nsample)
summary(water)

# mean number of sun hours per week
sun_mean = 21

# sd sun hours per week
sun_sd = 7

# sun hours per week
sun = rnorm(mean=sun_mean, sd=sun_sd, n=nsample)
summary(sun)

# combine sun and water data into one df
inputs_df <- data.frame(water = water, sun = sun)

```


```{r forloop}
# create empty data frame for growth outputs - incremental
growth_df <- data.frame(growth = numeric(length(sun)), leaves = numeric(length(sun)))

for (i in 1:nrow(inputs_df)) {
  growth_df[i,] = compute_plant_growth(sun=inputs_df$sun[i], water=inputs_df$water[i], pot=1)
  
}

head(growth_df)
```

```{r}
# separate data generated for pmap
# waterings per week
water2 = rnorm(mean=water_mean, sd=water_sd, n=nsample)
summary(water2)

# sun hours per week
sun2 = rnorm(mean=sun_mean, sd=sun_sd, n=nsample)
summary(sun2)

# combine sun and water data into one df
inputs_df2 <- data.frame(water = water2, sun = sun2)

```

```{r purrr::pmap()}
# use pmap_dfc to apply plant growth function to inputs 
growth_df2 <- pmap_dfc(list(inputs_df2$sun, inputs_df2$water, rep(1, nrow(inputs_df2))), compute_plant_growth) %>% 
  matrix(ncol = 2, byrow = TRUE) %>%
  as.data.frame() %>% 
  rename(growth =1, leaves =2)

head(growth_df2)
```

```{r}
# Combine inputs_df and growth data output into one df
all_growth_df <- cbind(inputs_df,growth_df)

# Add a line graph to plot growth over time based on sunlight per week
plot_1= ggplot(growth_df, aes(x = sun, y = growth, color = growth))+
  geom_line() + geom_point() +
  labs(x = "Amount of Sun (hours per week)", y = "Plant Growth (mm)", title = "Plant growth over time based on Sunlight Availability")+
  theme_minimal()+ 
  theme(legend.position = "none")

plot_1
```


