---
title: "Assignment 4 - Bonus"
author: "Sage Davis"
date: "2023-03-07"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)


```

```{r}

# Read in data
#fish_data <- read.delim("fish.txt")

# convert data frame to vector
#catch_vector <- c(fish_data$x)



```

```{r}
# generate some data if we had 10 different fishing days
# some examples of using the purr family of functions

possible.fish=c("salmon","steelhead","shark","tuna","cod")
# lets generate random sample of the number of fish caught on each day
ndays=10
catches=round(runif(min=3,max=400,n=ndays))

# now for each fishing day (and its number of fish caught) - use sample to generate the fish
catches_res=list(catches) %>% 
  pmap(sample,x=possible.fish,replace=TRUE)

# look at the sample catches
catches_res[[5]]
```


```{r}

# Call in function to calculate max, min and total species
source("../R/fishing.R")

# Use function to calculate max, min and total species for read in data for each catch_res[[i]]
# using a for loop

# fish = pmap(catches_res, diversity)

#for (i in 1:10) {
 # fish = diversity(catches_res[[i]])
#}
catch_vec <- as.vector(catches_res)
catch_mat <- as.matrix(catches_res)

fish <- lapply(catches_res, diversity)
print(fish)

```

